const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Destination = require('../models/Destination');
const Hotel = require('../models/Hotel');
const User = require('../models/User');
const Product = require('../models/Product');

dotenv.config();

const toSlug = (name) => name.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]/g, '');

const destinations = [
  // ── HISTORICAL ─────────────────────────────────────────────────────
  {
    name: 'Taj Mahal',
    slug: toSlug('Taj Mahal'),
    district: 'Agra',
    category: 'historical',
    description: 'The Taj Mahal is an ivory-white marble mausoleum on the right bank of the river Yamuna in Agra. Commissioned in 1632 by Mughal emperor Shah Jahan to house the tomb of his beloved wife Mumtaz Mahal, it took 22 years and 20,000 artisans to complete. Widely considered one of the greatest architectural achievements in the world, it was designated a UNESCO World Heritage Site in 1983.',
    shortDescription: 'UNESCO World Heritage Site and one of the Seven Wonders of the World.',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Taj_Mahal_%28Edited%29.jpeg/1200px-Taj_Mahal_%28Edited%29.jpeg',
    images: [],
    entryFee: { indian: 50, foreign: 1100 },
    timings: { open: '06:00 AM', close: '07:00 PM', closedOn: 'Friday' },
    bestTimeToVisit: 'October to March',
    highlights: ['Sunrise view', 'Mughal architecture', 'Yamuna river view', 'Museum inside', 'Moonlight viewing'],
    tags: ['mughal', 'wonder', 'marble', 'love', 'unesco'],
    isFeatured: true, rating: 4.9, reviewCount: 1520, viewCount: 8400,
    location: { address: 'Dharmapuri, Tajganj, Agra', latitude: 27.1751, longitude: 78.0421 },
  },
  {
    name: 'Agra Fort',
    slug: toSlug('Agra Fort'),
    district: 'Agra',
    category: 'historical',
    description: 'Agra Fort is a UNESCO World Heritage Site and a massive red sandstone fortification that served as the main residence of the Mughal emperors until 1638. The fort contains a number of palaces, mosques, and audience halls built over the reigns of Akbar, Jahangir, and Shah Jahan. Shah Jahan was imprisoned here by his son Aurangzeb and spent his final years gazing at the Taj Mahal across the river.',
    shortDescription: 'Magnificent Mughal fortification where Shah Jahan spent his final days.',
    coverImage: 'https://cdn.create.vista.com/api/media/small/146956591/stock-photo-agra-fort-a-unesco-world-heritage-site-in-the-city-of-agra-india',
    images: [],
    entryFee: { indian: 40, foreign: 550 },
    timings: { open: '06:00 AM', close: '06:00 PM', closedOn: 'None' },
    bestTimeToVisit: 'October to March',
    highlights: ['Diwan-i-Am', 'Diwan-i-Khas', 'Musamman Burj', 'Jahangiri Mahal', 'Taj Mahal view'],
    tags: ['mughal', 'fort', 'akbar', 'sandstone', 'unesco'],
    isFeatured: false, rating: 4.6, reviewCount: 890, viewCount: 4200,
    location: { address: 'Agra Fort, Agra', latitude: 27.1800, longitude: 78.0219 },
  },
  {
    name: 'Fatehpur Sikri',
    slug: toSlug('Fatehpur Sikri'),
    district: 'Agra',
    category: 'heritage',
    description: 'Fatehpur Sikri is a walled city and UNESCO World Heritage Site built by Emperor Akbar in the late 16th century as the capital of the Mughal Empire. The city was abandoned after only 14 years, possibly due to water scarcity. It remains one of the best-preserved examples of Mughal architecture and town planning, built entirely in red sandstone.',
    shortDescription: 'Abandoned Mughal capital with stunning red sandstone architecture.',
    coverImage: 'https://www.ancient-origins.net/sites/default/files/styles/large/public/abandoned_1.jpg?itok=uThfOPtz',
    images: [],
    entryFee: { indian: 40, foreign: 600 },
    timings: { open: '06:00 AM', close: '06:00 PM', closedOn: 'None' },
    bestTimeToVisit: 'October to March',
    highlights: ['Buland Darwaza', 'Jama Masjid', 'Diwan-i-Khas', 'Panch Mahal', 'Salim Chishti Tomb'],
    tags: ['mughal', 'akbar', 'sandstone', 'unesco', 'abandoned'],
    isFeatured: false, rating: 4.5, reviewCount: 420, viewCount: 3100,
    location: { address: 'Fatehpur Sikri, Agra', latitude: 27.0945, longitude: 77.6580 },
  },
  {
    name: 'Sarnath',
    slug: toSlug('Sarnath'),
    district: 'Varanasi',
    category: 'historical',
    description: 'Sarnath is the deer park where Gautama Buddha first taught the Dharma after attaining enlightenment at Bodh Gaya. Known as the site of the first turning of the wheel of Dharma, it is one of the four most important Buddhist pilgrimage sites. The Dhamek Stupa dating to 500 CE and the Ashoka Pillar — whose lion capital became India\'s national emblem — stand here.',
    shortDescription: 'Where Buddha gave his first sermon — a key Buddhist pilgrimage site.',
    coverImage: 'https://www.tripsavvy.com/thmb/43eExCq5xu3ASm40YMqfebX6kfU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/GettyImages-11277274181-f11cfdb1a6514121aa39eea112917faf.jpg',
    images: [],
    entryFee: { indian: 15, foreign: 200 },
    timings: { open: '09:00 AM', close: '05:00 PM', closedOn: 'None' },
    bestTimeToVisit: 'November to February',
    highlights: ['Dhamek Stupa', 'Ashoka Pillar', 'Sarnath Museum', 'Thai Temple', 'Deer Park'],
    tags: ['buddhist', 'buddha', 'stupa', 'pilgrimage', 'peace'],
    isFeatured: false, rating: 4.4, reviewCount: 310, viewCount: 2200,
    location: { address: 'Sarnath, Varanasi', latitude: 25.3813, longitude: 83.0240 },
  },
  {
    name: 'Allahabad Fort',
    slug: toSlug('Allahabad Fort'),
    district: 'Prayagraj',
    category: 'historical',
    description: 'Allahabad Fort, also called Prayagraj Fort, is one of the largest forts built by Emperor Akbar, located at the confluence of the Ganga, Yamuna and mythical Saraswati rivers. Built in 1583, it houses the famous Ashoka Pillar, the underground Patalpuri Temple, and the sacred Akshayavat (immortal banyan tree). The fort is partially occupied by the Indian Army and only certain sections are open to tourists.',
    shortDescription: 'Akbar\'s grand fort at the holy Triveni Sangam confluence.',
    coverImage: 'https://media.gettyimages.com/id/140177539/photo/india-uttar-pradesh-allahabad-akbars-fort.jpg?s=612x612&w=0&k=20&c=TmDy9xPK0raULEQ59lMF9bIhu0xSpSN4I6JkVwCe00E=',
    images: [],
    entryFee: { indian: 20, foreign: 200 },
    timings: { open: '08:00 AM', close: '05:00 PM', closedOn: 'None' },
    bestTimeToVisit: 'October to February',
    highlights: ['Ashoka Pillar', 'Patalpuri Temple', 'Akshayavat', 'Saraswati Koop', 'River confluence view'],
    tags: ['akbar', 'fort', 'prayagraj', 'sangam', 'mughal'],
    isFeatured: false, rating: 4.2, reviewCount: 280, viewCount: 1800,
    location: { address: 'Prayagraj Fort, Prayagraj', latitude: 25.4358, longitude: 81.8463 },
  },

  // ── RELIGIOUS ──────────────────────────────────────────────────────
  {
    name: 'Varanasi Ghats',
    slug: toSlug('Varanasi Ghats'),
    district: 'Varanasi',
    category: 'religious',
    description: 'Varanasi, the spiritual capital of India, is one of the oldest continuously inhabited cities in the world. The 84 ghats stretch along the western bank of the Ganga, each with its own history and significance. The Ganga Aarti at Dashashwamedh Ghat is a breathtaking nightly ceremony. Hindus believe dying in Varanasi grants moksha — liberation from the cycle of rebirth.',
    shortDescription: 'Ancient spiritual city with iconic ghats along the sacred river Ganga.',
    coverImage: 'https://www.savaari.com/blog/wp-content/uploads/2023/09/Varanasi_ghats1.webp',
    images: [],
    entryFee: { indian: 0, foreign: 0 },
    timings: { open: '04:00 AM', close: '10:00 PM', closedOn: 'None' },
    bestTimeToVisit: 'November to February',
    highlights: ['Ganga Aarti at Dashashwamedh Ghat', 'Boat ride at sunrise', 'Kashi Vishwanath Temple', 'Manikarnika Ghat', 'Assi Ghat'],
    tags: ['spiritual', 'ganga', 'ghats', 'aarti', 'pilgrimage', 'moksha'],
    isFeatured: true, rating: 4.7, reviewCount: 980, viewCount: 6200,
    location: { address: 'Dashashwamedh Ghat, Varanasi', latitude: 25.3176, longitude: 83.0062 },
  },
  {
    name: 'Ram Janmabhoomi',
    slug: toSlug('Ram Janmabhoomi'),
    district: 'Ayodhya',
    category: 'religious',
    description: 'Ayodhya is one of the seven holy cities of Hinduism and the birthplace of Lord Ram, hero of the Ramayana. The newly constructed Ram Mandir, inaugurated in January 2024, is a grand temple built in Nagara style of architecture and has quickly become one of India\'s most visited religious sites. The city also features the Saryu River ghats, Hanuman Garhi temple, and Kanak Bhawan.',
    shortDescription: 'Birthplace of Lord Ram, home to the grand new Ram Mandir.',
    coverImage: 'https://cdn.britannica.com/56/254056-004-C8A48AC8/New-Hindu-Ram-Temple-under-construction-Ayodhya-India.jpg',
    images: [],
    entryFee: { indian: 0, foreign: 0 },
    timings: { open: '05:00 AM', close: '11:00 PM', closedOn: 'None' },
    bestTimeToVisit: 'October to March',
    highlights: ['Ram Mandir', 'Saryu River Aarti', 'Hanuman Garhi', 'Kanak Bhawan', 'Ram Ki Paidi'],
    tags: ['ram', 'temple', 'pilgrimage', 'ayodhya', 'mandir', 'ramayana'],
    isFeatured: true, rating: 4.8, reviewCount: 750, viewCount: 5500,
    location: { address: 'Ram Janmabhoomi, Ayodhya', latitude: 26.7922, longitude: 82.1998 },
  },
  {
    name: 'Mathura Vrindavan',
    slug: toSlug('Mathura Vrindavan'),
    district: 'Mathura',
    category: 'religious',
    description: 'Mathura is the birthplace of Lord Krishna and one of the seven sacred cities in Hinduism. Together with Vrindavan — the town where Krishna spent his childhood — it forms one of India\'s most important pilgrimage circuits. The region has over 5,000 temples. Vrindavan\'s Banke Bihari Temple, ISKCON Temple, and the Prem Mandir are must-visits. Holi celebrations here are legendary.',
    shortDescription: 'Birthplace of Lord Krishna — sacred twin cities of Mathura and Vrindavan.',
    coverImage: 'https://propacity.com/blogs/wp-content/uploads/2024/06/Prem-Mandir-2.jpg',
    images: [],
    entryFee: { indian: 0, foreign: 0 },
    timings: { open: '05:00 AM', close: '09:00 PM', closedOn: 'None' },
    bestTimeToVisit: 'October to March, Holi festival',
    highlights: ['Krishna Janmabhoomi Temple', 'Banke Bihari Temple', 'Prem Mandir', 'ISKCON Temple', 'Yamuna Aarti'],
    tags: ['krishna', 'temple', 'holi', 'vrindavan', 'pilgrimage'],
    isFeatured: true, rating: 4.6, reviewCount: 650, viewCount: 4800,
    location: { address: 'Mathura, Uttar Pradesh', latitude: 27.4924, longitude: 77.6737 },
  },
  {
    name: 'Triveni Sangam',
    slug: toSlug('Triveni Sangam'),
    district: 'Prayagraj',
    category: 'religious',
    description: 'Triveni Sangam is the confluence of three rivers — Ganga, Yamuna, and the mythical Saraswati. It is considered one of the holiest spots in Hinduism. The Kumbh Mela, held here every 12 years, is the largest peaceful gathering of people on Earth. Pilgrims take a holy dip believing it cleanses all sins. Boating on the Sangam offers a unique view of where the rivers meet.',
    shortDescription: 'Sacred confluence of three rivers, host of the mighty Kumbh Mela.',
    coverImage: 'https://s7ap1.scene7.com/is/image/incredibleindia/triveni-sangam-prayagraj-uttar-pradesh-1-attr-hero?qlt=82&ts=1751459171785',
    images: [],
    entryFee: { indian: 0, foreign: 0 },
    timings: { open: '05:00 AM', close: '08:00 PM', closedOn: 'None' },
    bestTimeToVisit: 'October to March, Kumbh Mela years',
    highlights: ['Holy dip at Sangam', 'Boat ride', 'Kumbh Mela ground', 'Hanuman Temple', 'Saraswati Ghat'],
    tags: ['sangam', 'kumbh', 'prayagraj', 'ganga', 'pilgrimage'],
    isFeatured: true, rating: 4.7, reviewCount: 820, viewCount: 5100,
    location: { address: 'Sangam, Prayagraj', latitude: 25.4244, longitude: 81.8845 },
  },
  {
    name: 'Vindhyachal',
    slug: toSlug('Vindhyachal'),
    district: 'Mirzapur',
    category: 'religious',
    description: 'Vindhyachal is one of the most important Shakti Peethas — shrines of the goddess. The Vindhyavasini Devi temple is visited by millions of devotees every year. Situated in the Vindhya mountain range near the Ganga, it is also significant for the nearby Ashtabhuja and Kali Khoh temples. The Navratri festival draws massive crowds here twice a year.',
    shortDescription: 'Ancient Shakti Peetha on the Vindhya mountains — sacred to goddess Vindhyavasini.',
    coverImage: 'https://cdn1.tripoto.com/media/filter/nl/img/2380291/Image/1701965207_banner_1024x576.jpg.webp',
    images: [],
    entryFee: { indian: 0, foreign: 0 },
    timings: { open: '04:00 AM', close: '10:00 PM', closedOn: 'None' },
    bestTimeToVisit: 'Navratri (March–April, Sept–Oct)',
    highlights: ['Vindhyavasini Devi Temple', 'Ashtabhuja Temple', 'Kali Khoh Temple', 'Ganga Ghat', 'Navratri festival'],
    tags: ['shakti', 'devi', 'temple', 'navratri', 'pilgrimage'],
    isFeatured: false, rating: 4.4, reviewCount: 380, viewCount: 2400,
    location: { address: 'Vindhyachal, Mirzapur', latitude: 25.1319, longitude: 82.5734 },
  },

  // ── HERITAGE ───────────────────────────────────────────────────────
  {
    name: 'Bara Imambara',
    slug: toSlug('Bara Imambara'),
    district: 'Lucknow',
    category: 'heritage',
    description: 'The Bara Imambara is a grand imambara complex in Lucknow built by Nawab Asaf-ud-Daula in 1784. It is famous for its Bhulbhulaiya — a unique labyrinthine maze on the roof with 489 identical passages. The central hall is one of the largest arched constructions in the world built without any iron girders. The complex also houses the Asafi Mosque and a unique stepwell.',
    shortDescription: 'Nawabi architecture gem with a famous rooftop maze — Bhulbhulaiya.',
    coverImage: 'https://t4.ftcdn.net/jpg/17/09/86/29/360_F_1709862952_PiQyOdgkMnBYmLQYVQMEGDNL9KhsifIa.jpg',
    images: [],
    entryFee: { indian: 25, foreign: 500 },
    timings: { open: '06:00 AM', close: '05:00 PM', closedOn: 'None' },
    bestTimeToVisit: 'October to March',
    highlights: ['Bhulbhulaiya maze', 'Asafi Mosque', 'Shahi Baoli', 'Nawabi architecture', 'Rumi Darwaza nearby'],
    tags: ['nawab', 'imambara', 'maze', 'lucknow', 'mughal'],
    isFeatured: true, rating: 4.5, reviewCount: 540, viewCount: 3800,
    location: { address: 'Husainabad, Lucknow', latitude: 26.8781, longitude: 80.9112 },
  },
  {
    name: 'Rumi Darwaza',
    slug: toSlug('Rumi Darwaza'),
    district: 'Lucknow',
    category: 'heritage',
    description: 'Rumi Darwaza is an imposing gateway in Lucknow, built in 1784 by Nawab Asaf-ud-Daula. Standing 60 feet tall, it was built in the Awadhi style of architecture and served as an entrance to the old city. Often called the Turkish Gate due to its resemblance to a gate in Istanbul, it is one of the most recognizable symbols of Lucknow and Awadhi culture.',
    shortDescription: 'The iconic 60-foot Nawabi gateway — symbol of Lucknow\'s heritage.',
    coverImage: 'https://images.herzindagi.info/image/2023/Jul/Story-Behind-Rumi-Darwaza.jpg',
    images: [],
    entryFee: { indian: 0, foreign: 0 },
    timings: { open: '06:00 AM', close: '08:00 PM', closedOn: 'None' },
    bestTimeToVisit: 'October to March',
    highlights: ['60-foot gateway', 'Awadhi architecture', 'Night lighting', 'Photography spot'],
    tags: ['nawab', 'lucknow', 'gateway', 'awadhi', 'architecture'],
    isFeatured: false, rating: 4.3, reviewCount: 290, viewCount: 2100,
    location: { address: 'Husainabad, Lucknow', latitude: 26.8767, longitude: 80.9120 },
  },

  // ── NATURE / WILDLIFE ──────────────────────────────────────────────
  {
    name: 'Dudhwa National Park',
    slug: toSlug('Dudhwa National Park'),
    district: 'Lakhimpur Kheri',
    category: 'nature',
    description: 'Dudhwa National Park is one of the finest examples of the terai ecosystem — dense forests, tall grasslands, and wetlands spread across 811 sq km on the India-Nepal border. It is home to tigers, rhinos (reintroduced), swamp deer (barasingha), leopards, elephants, and over 400 species of birds. Dudhwa is the only place in UP where you can see the one-horned rhinoceros in the wild.',
    shortDescription: 'UP\'s premier tiger reserve — home to rhinos, tigers and the rare barasingha.',
    coverImage: 'https://www.tigersafari.net/wp-content/uploads/2022/09/dudhwa-national-park-1024x576.jpg',
    images: [],
    entryFee: { indian: 200, foreign: 1500 },
    timings: { open: '06:00 AM', close: '05:00 PM', closedOn: 'Park closed June to mid-November' },
    bestTimeToVisit: 'November to May',
    highlights: ['Tiger safari', 'One-horned rhino', 'Barasingha deer', 'Elephant rides', 'Bird watching'],
    tags: ['wildlife', 'tiger', 'rhino', 'safari', 'jungle', 'nature'],
    isFeatured: true, rating: 4.5, reviewCount: 340, viewCount: 2900,
    location: { address: 'Dudhwa, Lakhimpur Kheri', latitude: 28.4997, longitude: 80.7529 },
  },
  {
    name: 'Chambal Safari',
    slug: toSlug('Chambal Safari'),
    district: 'Agra',
    category: 'nature',
    description: 'The Chambal River and its ravines near Agra offer one of India\'s most unique wildlife experiences. The National Chambal Sanctuary is home to the critically endangered Gharial crocodile, the Indian skimmer bird, Gangetic dolphins, and marsh mugger crocodiles. Boat safaris along the Chambal are the best way to spot these rare species in a stunning ravine landscape.',
    shortDescription: 'Boat safaris on the Chambal river — spot gharials, dolphins and rare birds.',
    coverImage: 'https://images.travelandleisureasia.com/wp-content/uploads/sites/2/2025/10/30170643/chambal-river-safari.jpg',
    images: [],
    entryFee: { indian: 150, foreign: 600 },
    timings: { open: '06:00 AM', close: '06:00 PM', closedOn: 'None' },
    bestTimeToVisit: 'October to March',
    highlights: ['Gharial crocodiles', 'Gangetic dolphins', 'Indian skimmer birds', 'Boat safari', 'Ravine landscape'],
    tags: ['wildlife', 'gharial', 'dolphin', 'safari', 'river', 'nature'],
    isFeatured: false, rating: 4.3, reviewCount: 180, viewCount: 1400,
    location: { address: 'Chambal Safari, near Agra', latitude: 26.9958, longitude: 78.4247 },
  },
  {
    name: 'Hastinapur Wildlife Sanctuary',
    slug: toSlug('Hastinapur Wildlife Sanctuary'),
    district: 'Meerut',
    category: 'nature',
    description: 'Hastinapur Wildlife Sanctuary encompasses the ancient Mahabharata-era city of Hastinapur and the surrounding wetlands on the Ganga floodplains. The sanctuary is a haven for migratory birds in winter, with hundreds of species visiting the wetlands. Gharials, Gangetic dolphins, and the fishing cat are among the key species. The area also holds great historical significance as the ancient Kuru capital.',
    shortDescription: 'Mahabharata-era city set in stunning wetlands rich with migratory birds.',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Migratory_Birds_At_Hastinapur.jpg',
    images: [],
    entryFee: { indian: 50, foreign: 300 },
    timings: { open: '07:00 AM', close: '05:00 PM', closedOn: 'None' },
    bestTimeToVisit: 'November to February (migratory birds)',
    highlights: ['Migratory birds', 'Gangetic dolphins', 'Ancient Hastinapur ruins', 'Wetland ecosystem', 'Fishing cat'],
    tags: ['wildlife', 'birds', 'wetlands', 'mahabharata', 'nature'],
    isFeatured: false, rating: 4.1, reviewCount: 120, viewCount: 980,
    location: { address: 'Hastinapur, Meerut', latitude: 29.1580, longitude: 78.0117 },
  },

  // ── CULTURAL ───────────────────────────────────────────────────────
  {
    name: 'Lucknow Residency',
    slug: toSlug('Lucknow Residency'),
    district: 'Lucknow',
    category: 'cultural',
    description: 'The Residency is a group of buildings in Lucknow that was the site of the Siege of Lucknow during the Indian Rebellion of 1857. The British garrison held out for 87 days against Indian sepoys and civilians. The ruins are preserved exactly as they were after the siege — bullet-riddled walls, damaged buildings, and a cemetery with over 2,000 graves. It is now a UNESCO-protected monument and a powerful reminder of India\'s struggle for independence.',
    shortDescription: 'Historic 1857 siege site — preserved ruins and a poignant museum of independence.',
    coverImage: 'https://staticimg.amarujala.com/assets/images/2019/02/16/residency_1550315406.jpeg?q=80',
    images: [],
    entryFee: { indian: 25, foreign: 300 },
    timings: { open: '07:00 AM', close: '05:00 PM', closedOn: 'Monday' },
    bestTimeToVisit: 'October to March',
    highlights: ['1857 ruins', 'Residency museum', 'Cemetery', 'Banquet hall ruins', 'Independence history'],
    tags: ['1857', 'independence', 'british', 'lucknow', 'history', 'museum'],
    isFeatured: false, rating: 4.2, reviewCount: 310, viewCount: 2000,
    location: { address: 'Residency Road, Lucknow', latitude: 26.8540, longitude: 80.9192 },
  },
];

const getHotels = (destMap) => [
  // ── Agra ─────────────────────────────────────────────────
  {
    name: 'The Oberoi Amarvilas',
    slug: toSlug('The Oberoi Amarvilas'),
    district: 'Agra', destination: destMap['Taj Mahal'],
    starRating: 5, type: 'luxury',
    description: 'Regarded as one of the finest hotels in the world, The Oberoi Amarvilas offers uninterrupted views of the Taj Mahal from every room and suite. Spread across nine acres of landscaped gardens with Mughal-inspired fountains and terraces.',
    coverImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
    images: [],
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Bar', 'Gym', 'Room Service', 'Valet Parking', 'Taj View'],
    pricePerNight: 45000,
    address: 'Taj East Gate Road, Agra',
    contactPhone: '+91-562-2231515',
    contactEmail: 'reservations.avy@oberoihotels.com',
    rating: 4.9, reviewCount: 320, totalRooms: 102, isActive: true,
  },
  {
    name: 'Trident Agra',
    slug: toSlug('Trident Agra'),
    district: 'Agra', destination: destMap['Taj Mahal'],
    starRating: 5, type: 'luxury',
    description: 'Set in 23 acres of Mughal-inspired gardens, Trident Agra offers elegant rooms with partial views of the Taj Mahal. Features a stunning outdoor pool surrounded by manicured lawns.',
    coverImage: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
    images: [],
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Tennis Court', 'Business Center'],
    pricePerNight: 12000,
    address: 'Taj Nagari, Agra',
    contactPhone: '+91-562-2330101',
    rating: 4.6, reviewCount: 210, totalRooms: 138, isActive: true,
  },
  {
    name: 'Hotel Kamal',
    slug: toSlug('Hotel Kamal'),
    district: 'Agra', destination: destMap['Taj Mahal'],
    starRating: 2, type: 'budget',
    description: 'A clean budget hotel a short walk from the Taj Mahal South Gate. Perfect for travellers who want proximity to the monument without spending a fortune.',
    coverImage: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
    images: [],
    amenities: ['WiFi', 'Restaurant', 'Room Service', 'Parking'],
    pricePerNight: 1200,
    address: 'South Gate, Taj Mahal, Agra',
    contactPhone: '+91-562-2330126',
    rating: 3.8, reviewCount: 145, totalRooms: 24, isActive: true,
  },
  {
    name: 'ITC Mughal Agra',
    slug: toSlug('ITC Mughal Agra'),
    district: 'Agra', destination: destMap['Agra Fort'],
    starRating: 5, type: 'luxury',
    description: 'ITC Mughal is a grand luxury resort in Agra spread over 35 acres, inspired by Mughal garden architecture. The hotel features the award-winning Kaya Kalp spa and multiple specialty restaurants serving Mughlai cuisine.',
    coverImage: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800',
    images: [],
    amenities: ['WiFi', 'Pool', 'Spa', 'Multiple Restaurants', 'Bar', 'Gym', 'Golf', 'Kaya Kalp Spa'],
    pricePerNight: 18000,
    address: 'Fatehabad Road, Agra',
    contactPhone: '+91-562-4021700',
    rating: 4.8, reviewCount: 290, totalRooms: 233, isActive: true,
  },

  // ── Varanasi ─────────────────────────────────────────────
  {
    name: 'Taj Ganges',
    slug: toSlug('Taj Ganges'),
    district: 'Varanasi', destination: destMap['Varanasi Ghats'],
    starRating: 5, type: 'luxury',
    description: 'An oasis of calm in the holy city of Varanasi, Taj Ganges combines modern luxury with the spiritual essence of Kashi. Features lush gardens and a dedicated concierge for temple visits and Ganga Aarti experiences.',
    coverImage: 'https://images.unsplash.com/photo-1618245318763-a15156d6b23c?w=800',
    images: [],
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Bar', 'Gym', 'Yoga Classes', 'Airport Transfer'],
    pricePerNight: 9500,
    address: 'Nadesar Palace Grounds, Varanasi',
    contactPhone: '+91-542-6660001',
    rating: 4.7, reviewCount: 180, totalRooms: 130, isActive: true,
  },
  {
    name: 'Brijrama Palace',
    slug: toSlug('Brijrama Palace'),
    district: 'Varanasi', destination: destMap['Varanasi Ghats'],
    starRating: 5, type: 'heritage',
    description: 'A 250-year-old heritage palace perched on the banks of the Ganga. Each room is uniquely decorated with antiques. Wake up to temple bells and watch the Ganga from your private balcony.',
    coverImage: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800',
    images: [],
    amenities: ['WiFi', 'Ganga View', 'Restaurant', 'Rooftop Terrace', 'Boat Rides', 'Yoga', 'Heritage Tours'],
    pricePerNight: 18000,
    address: 'Darbhanga Ghat, Varanasi',
    contactPhone: '+91-542-2390000',
    rating: 4.8, reviewCount: 95, totalRooms: 32, isActive: true,
  },
  {
    name: 'Hotel Alka',
    slug: toSlug('Hotel Alka'),
    district: 'Varanasi', destination: destMap['Varanasi Ghats'],
    starRating: 2, type: 'budget',
    description: 'Simple ghat-facing rooms perfect for pilgrims and backpackers. The rooftop restaurant offers stunning sunrise views of the Ganga.',
    coverImage: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
    images: [],
    amenities: ['WiFi', 'Ganga View', 'Rooftop Restaurant', 'Laundry'],
    pricePerNight: 800,
    address: 'Meer Ghat, Varanasi',
    rating: 3.6, reviewCount: 220, totalRooms: 18, isActive: true,
  },

  // ── Lucknow ──────────────────────────────────────────────
  {
    name: 'Taj Mahal Lucknow',
    slug: toSlug('Taj Mahal Lucknow'),
    district: 'Lucknow', destination: destMap['Bara Imambara'],
    starRating: 5, type: 'luxury',
    description: 'The finest address in Lucknow, offering world-class amenities with Nawabi-inspired architecture and legendary Taj hospitality.',
    coverImage: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
    images: [],
    amenities: ['WiFi', 'Pool', 'Spa', 'Multiple Restaurants', 'Bar', 'Gym', 'Business Center'],
    pricePerNight: 8000,
    address: 'Vipin Khand, Gomti Nagar, Lucknow',
    contactPhone: '+91-522-6671000',
    rating: 4.7, reviewCount: 260, totalRooms: 196, isActive: true,
  },
  {
    name: 'Lebua Lucknow',
    slug: toSlug('Lebua Lucknow'),
    district: 'Lucknow', destination: destMap['Bara Imambara'],
    starRating: 4, type: 'mid-range',
    description: 'Boutique hotel in Hazratganj combining contemporary design with Awadhi hospitality. Known for excellent Awadhi cuisine.',
    coverImage: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
    images: [],
    amenities: ['WiFi', 'Restaurant', 'Bar', 'Gym', 'Conference Room', 'Rooftop'],
    pricePerNight: 4500,
    address: 'Hazratganj, Lucknow',
    rating: 4.3, reviewCount: 140, totalRooms: 55, isActive: true,
  },

  // ── Ayodhya ──────────────────────────────────────────────
  {
    name: 'Ramayana Hotel',
    slug: toSlug('Ramayana Hotel'),
    district: 'Ayodhya', destination: destMap['Ram Janmabhoomi'],
    starRating: 3, type: 'mid-range',
    description: 'Comfortable hotel near the Ram Mandir complex serving only sattvic vegetarian food, with a calm devotional atmosphere.',
    coverImage: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
    images: [],
    amenities: ['WiFi', 'Sattvic Restaurant', 'Prayer Hall', 'Parking', 'Meditation Room'],
    pricePerNight: 2500,
    address: 'Near Ram Mandir, Ayodhya',
    contactPhone: '+91-5278-232323',
    rating: 4.1, reviewCount: 190, totalRooms: 40, isActive: true,
  },
  {
    name: 'WelcomHotel Ayodhya',
    slug: toSlug('WelcomHotel Ayodhya'),
    district: 'Ayodhya', destination: destMap['Ram Janmabhoomi'],
    starRating: 4, type: 'luxury',
    description: 'Modern luxury hotel with rooftop infinity pool overlooking the Saryu river and dedicated pilgrimage concierge service.',
    coverImage: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800',
    images: [],
    amenities: ['WiFi', 'Infinity Pool', 'Spa', 'Restaurant', 'Gym', 'Saryu View', 'Pilgrimage Concierge'],
    pricePerNight: 6500,
    address: 'Saryu Ghat Road, Ayodhya',
    rating: 4.5, reviewCount: 88, totalRooms: 80, isActive: true,
  },

  // ── Mathura ──────────────────────────────────────────────
  {
    name: 'Radha Ashok Hotel',
    slug: toSlug('Radha Ashok Hotel'),
    district: 'Mathura', destination: destMap['Mathura Vrindavan'],
    starRating: 4, type: 'mid-range',
    description: 'A premium hotel in Mathura offering comfortable rooms near the Krishna Janmabhoomi temple complex. The hotel is themed around Krishna\'s life with beautiful artwork throughout.',
    coverImage: 'https://images.unsplash.com/photo-1618245318763-a15156d6b23c?w=800',
    images: [],
    amenities: ['WiFi', 'Vegetarian Restaurant', 'Pool', 'Gym', 'Temple Tours', 'Parking'],
    pricePerNight: 3500,
    address: 'Janmabhoomi Road, Mathura',
    contactPhone: '+91-565-2400234',
    rating: 4.2, reviewCount: 165, totalRooms: 68, isActive: true,
  },
  {
    name: 'ISKCON Guesthouse Vrindavan',
    slug: toSlug('ISKCON Guesthouse Vrindavan'),
    district: 'Mathura', destination: destMap['Mathura Vrindavan'],
    starRating: 2, type: 'budget',
    description: 'Simple, clean guesthouse run by ISKCON inside the temple campus in Vrindavan. Perfect for devotees and spiritual seekers. Only sattvic prasadam food served.',
    coverImage: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
    images: [],
    amenities: ['WiFi', 'Prasadam Restaurant', 'Temple Access', 'Meditation Hall'],
    pricePerNight: 600,
    address: 'ISKCON Temple, Vrindavan',
    rating: 4.0, reviewCount: 310, totalRooms: 80, isActive: true,
  },

  // ── Prayagraj ────────────────────────────────────────────
  {
    name: 'Kumbh Sarai',
    slug: toSlug('Kumbh Sarai'),
    district: 'Prayagraj', destination: destMap['Triveni Sangam'],
    starRating: 4, type: 'mid-range',
    description: 'A boutique heritage hotel in Prayagraj inspired by the tradition of dharmshalas near pilgrimage sites. Tastefully decorated with local art and close to the Triveni Sangam.',
    coverImage: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
    images: [],
    amenities: ['WiFi', 'Restaurant', 'Garden', 'Sangam Tours', 'Yoga', 'Parking'],
    pricePerNight: 3800,
    address: 'Civil Lines, Prayagraj',
    rating: 4.3, reviewCount: 112, totalRooms: 30, isActive: true,
  },

  // ── Nature / Wildlife ────────────────────────────────────
  {
    name: 'Dudhwa Forest Rest House',
    slug: toSlug('Dudhwa Forest Rest House'),
    district: 'Lakhimpur Kheri', destination: destMap['Dudhwa National Park'],
    starRating: 2, type: 'resort',
    description: 'The official forest rest house inside Dudhwa National Park, run by the UP Forest Department. Basic but comfortable rooms surrounded by jungle. The best way to experience Dudhwa is to stay here and go on early morning safaris.',
    coverImage: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
    images: [],
    amenities: ['Meals Included', 'Safari Booking', 'Nature Walks', 'Bird Watching', 'Forest Guide'],
    pricePerNight: 2000,
    address: 'Dudhwa National Park, Lakhimpur Kheri',
    contactPhone: '+91-5872-252106',
    rating: 4.0, reviewCount: 78, totalRooms: 12, isActive: true,
  },
  {
    name: 'Tiger Haven Resort',
    slug: toSlug('Tiger Haven Resort'),
    district: 'Lakhimpur Kheri', destination: destMap['Dudhwa National Park'],
    starRating: 3, type: 'resort',
    description: 'A private eco-resort near Dudhwa National Park offering comfortable jungle-themed cottages and exclusive wildlife experiences. Named after the famous conservationist Billy Arjan Singh who lived here.',
    coverImage: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
    images: [],
    amenities: ['WiFi', 'Meals Included', 'Jeep Safari', 'Elephant Safari', 'Birdwatching', 'Naturalist Guide', 'Campfire'],
    pricePerNight: 4500,
    address: 'Near Dudhwa Gate, Lakhimpur Kheri',
    rating: 4.4, reviewCount: 95, totalRooms: 20, isActive: true,
  },
];

const getProducts = (destMap) => [
  // ── Agra — Marble & Mughal crafts ────────────────────
  {
    name: 'Taj Mahal Marble Inlay Box',
    slug: 'taj-mahal-marble-inlay-box-' + Date.now(),
    destination: destMap['Taj Mahal'],
    district: 'Agra',
    category: 'handicraft',
    description: 'Hand-crafted white marble box with intricate pietra dura (stone inlay) work — the same technique used to build the Taj Mahal. Each piece takes 3–7 days to make and features semi-precious stones like malachite, lapis lazuli and turquoise forming floral patterns.',
    shortDescription: 'Handmade marble inlay box using Taj Mahal\'s pietra dura technique.',
    price: 1200,
    originalPrice: 1800,
    coverImage: 'https://5.imimg.com/data5/SELLER/Default/2022/10/DG/ZM/EA/115491097/20210926-121106-500x500.jpg',
    seller: { name: 'Agra Marble Arts', contact: '+91-9876543210', address: 'Taj Nagari, Agra' },
    stock: 40,
    rating: 4.7,
    reviewCount: 85,
    tags: ['marble', 'inlay', 'handicraft', 'taj mahal', 'gift'],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Agra Petha Gift Box (Assorted)',
    slug: 'agra-petha-gift-box-' + Date.now() + 1,
    destination: destMap['Taj Mahal'],
    district: 'Agra',
    category: 'food',
    description: 'Agra\'s most famous sweet — Petha — in an assorted gift box. Includes classic white, angoori (grape-shaped), kesar (saffron), and chocolate variants. Made fresh using traditional methods from ash gourd. Best bought from Panchhi Petha, Agra\'s most iconic petha shop.',
    shortDescription: 'Famous Agra petha in assorted flavours — the city\'s most iconic sweet.',
    price: 350,
    originalPrice: 400,
    coverImage: 'https://m.media-amazon.com/images/I/61Hi2jkT4JL.jpg',
    seller: { name: 'Panchhi Sweets', contact: '+91-9876543211', address: 'Sadar Bazar, Agra' },
    stock: 100,
    rating: 4.8,
    reviewCount: 210,
    tags: ['petha', 'sweet', 'food', 'agra', 'gift'],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Mughal Miniature Painting',
    slug: 'mughal-miniature-painting-' + Date.now() + 2,
    destination: destMap['Taj Mahal'],
    district: 'Agra',
    category: 'artwork',
    description: 'Authentic Mughal-style miniature painting on ivory sheet (bone paper) depicting scenes from royal Mughal life. Hand-painted by local artists using traditional pigments and fine squirrel-hair brushes. Each painting is unique and signed by the artist.',
    shortDescription: 'Authentic hand-painted Mughal miniature on ivory sheet.',
    price: 2500,
    originalPrice: 3500,
    coverImage: 'https://www.artzolo.com/cdn/shop/collections/own-a-piece-of-history-buy-mughal-miniature-paintings-artzolo-com.jpg?v=1726999110&width=800',
    seller: { name: 'Mughal Art Gallery', contact: '+91-9876543212', address: 'Kinari Bazar, Agra' },
    stock: 20,
    rating: 4.6,
    reviewCount: 45,
    tags: ['painting', 'mughal', 'miniature', 'art', 'handmade'],
    isFeatured: false,
    isActive: true,
  },

  // ── Varanasi — Silk & Spiritual ───────────────────────
  {
    name: 'Banarasi Silk Dupatta',
    slug: 'banarasi-silk-dupatta-' + Date.now() + 3,
    destination: destMap['Varanasi Ghats'],
    district: 'Varanasi',
    category: 'clothing',
    description: 'Pure Banarasi silk dupatta woven on handloom with real zari (gold thread) work. Varanasi\'s silk weaving tradition is over 400 years old and a GI-tagged product. This dupatta features traditional buta (floral motif) pattern in rich jewel tones. Comes with a certificate of authenticity.',
    shortDescription: 'Pure handloom Banarasi silk with real zari — GI-tagged authentic weave.',
    price: 3500,
    originalPrice: 5000,
    coverImage: 'https://thebanarasistyle.in/cdn/shop/files/IMG_3420_600x.heic?v=1771325078',
    seller: { name: 'Varanasi Weavers Co-op', contact: '+91-9876543213', address: 'Vishwanath Gali, Varanasi' },
    stock: 30,
    rating: 4.9,
    reviewCount: 130,
    tags: ['silk', 'banarasi', 'dupatta', 'zari', 'GI tagged'],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Ganga Aarti Puja Thali Set',
    slug: 'ganga-aarti-puja-thali-' + Date.now() + 4,
    destination: destMap['Varanasi Ghats'],
    district: 'Varanasi',
    category: 'spiritual',
    description: 'Complete brass puja thali set used in the iconic Ganga Aarti ceremony. Includes one large brass thali, five diyas (oil lamps), an incense holder, a small bell, and a conch shell. Handcrafted by Varanasi artisans and blessed at Dashashwamedh Ghat.',
    shortDescription: 'Complete brass puja thali set for Ganga Aarti — handcrafted in Varanasi.',
    price: 850,
    originalPrice: 1100,
    coverImage: 'https://images.unsplash.com/photo-1609893498571-7a45f71e5fe0?w=500',
    seller: { name: 'Kashi Spiritual Store', contact: '+91-9876543214', address: 'Dashashwamedh Ghat, Varanasi' },
    stock: 60,
    rating: 4.7,
    reviewCount: 98,
    tags: ['puja', 'aarti', 'brass', 'spiritual', 'varanasi'],
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Rudraksha Mala (108 beads)',
    slug: 'rudraksha-mala-108-' + Date.now() + 5,
    destination: destMap['Varanasi Ghats'],
    district: 'Varanasi',
    category: 'spiritual',
    description: 'Authentic 5-mukhi (5-faced) Rudraksha mala with 108 beads — the sacred number in Hinduism and Buddhism. Sourced from Nepal and strung with silk thread in Varanasi. Each bead is naturally shaped. Comes in a silk pouch with a certificate of origin. A powerful tool for meditation and prayer.',
    shortDescription: 'Authentic 5-mukhi Rudraksha mala — 108 beads, sourced from Nepal.',
    price: 650,
    originalPrice: 900,
    coverImage: 'https://images.unsplash.com/photo-1602526430780-782d6b1783fa?w=500',
    seller: { name: 'Shiv Shakti Rudraksha', contact: '+91-9876543215', address: 'Godaulia, Varanasi' },
    stock: 80,
    rating: 4.8,
    reviewCount: 175,
    tags: ['rudraksha', 'mala', 'spiritual', 'meditation', 'prayer'],
    isFeatured: true,
    isActive: true,
  },

  // ── Lucknow — Chikankari & Nawabi ────────────────────
  {
    name: 'Chikankari Kurta (White)',
    slug: 'chikankari-kurta-white-' + Date.now() + 6,
    destination: destMap['Bara Imambara'],
    district: 'Lucknow',
    category: 'clothing',
    description: 'Authentic Lucknow Chikankari hand-embroidered kurta in fine white cotton. Chikankari is a 400-year-old embroidery tradition developed in the courts of the Nawabs of Awadh. Each kurta takes skilled artisans 3–5 days to complete. GI-tagged product. Available in sizes S, M, L, XL.',
    shortDescription: 'Authentic hand-embroidered Lucknow Chikankari kurta — GI-tagged.',
    price: 1800,
    originalPrice: 2500,
    coverImage: 'https://images.unsplash.com/photo-1624284701699-caba1e987700?w=500',
    seller: { name: 'Lucknow Chikan Emporium', contact: '+91-9876543216', address: 'Aminabad, Lucknow' },
    stock: 35,
    rating: 4.8,
    reviewCount: 120,
    tags: ['chikankari', 'kurta', 'lucknow', 'embroidery', 'GI tagged'],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Lucknow Makkhan Malai (Recipe Box)',
    slug: 'lucknow-makkhan-malai-recipe-' + Date.now() + 7,
    destination: destMap['Bara Imambara'],
    district: 'Lucknow',
    category: 'food',
    description: 'Makkhan Malai is Lucknow\'s legendary winter dessert — a cloud-like sweet made from whipped cream, dew drops and saffron. This recipe kit includes all dry ingredients, saffron from Kashmir, and a recipe card to recreate this Nawabi delicacy at home. A unique gift from the City of Nawabs.',
    shortDescription: 'Recipe kit for Lucknow\'s legendary Makkhan Malai dessert.',
    price: 450,
    originalPrice: 550,
    coverImage: 'https://images.unsplash.com/photo-1571167366136-b57658e75c08?w=500',
    seller: { name: 'Nawabi Kitchen', contact: '+91-9876543217', address: 'Hazratganj, Lucknow' },
    stock: 50,
    rating: 4.5,
    reviewCount: 67,
    tags: ['food', 'dessert', 'lucknow', 'nawabi', 'sweet'],
    isFeatured: false,
    isActive: true,
  },

  // ── Mathura — Krishna items ───────────────────────────
  {
    name: 'Mathura Peda Gift Box',
    slug: 'mathura-peda-gift-box-' + Date.now() + 8,
    destination: destMap['Mathura Vrindavan'],
    district: 'Mathura',
    category: 'food',
    description: 'Mathura\'s most famous offering — the milk-based Peda sweet. This premium gift box contains 500g of freshly made pedas in three varieties: classic, kesar (saffron), and chocolate. Made from pure desi cow milk using a 200-year-old recipe. Best consumed within 5 days.',
    shortDescription: 'Mathura\'s famous milk-based Peda — offered to Lord Krishna for centuries.',
    price: 280,
    originalPrice: 320,
    coverImage: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500',
    seller: { name: 'Brijwasi Sweets', contact: '+91-9876543218', address: 'Vishram Ghat, Mathura' },
    stock: 120,
    rating: 4.9,
    reviewCount: 340,
    tags: ['peda', 'sweet', 'mathura', 'krishna', 'prasad'],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Brass Krishna Idol (6 inch)',
    slug: 'brass-krishna-idol-6inch-' + Date.now() + 9,
    destination: destMap['Mathura Vrindavan'],
    district: 'Mathura',
    category: 'spiritual',
    description: 'Hand-cast brass idol of Lord Krishna playing the flute (Murli Krishna pose), 6 inches tall. Made by traditional Mathura brass artisans using the lost-wax casting technique. Each idol is individually finished and polished. Comes in a velvet box with a puja booklet.',
    shortDescription: 'Hand-cast brass Murli Krishna idol — made by Mathura\'s traditional artisans.',
    price: 950,
    originalPrice: 1200,
    coverImage: 'https://images.unsplash.com/photo-1609893498571-7a45f71e5fe0?w=500',
    seller: { name: 'Mathura Brass Works', contact: '+91-9876543219', address: 'Chowk Bazar, Mathura' },
    stock: 45,
    rating: 4.7,
    reviewCount: 88,
    tags: ['krishna', 'brass', 'idol', 'spiritual', 'handmade'],
    isFeatured: false,
    isActive: true,
  },

  // ── Ayodhya — Ram temple items ────────────────────────
  {
    name: 'Ram Mandir Prasad Box',
    slug: 'ram-mandir-prasad-box-' + Date.now() + 10,
    destination: destMap['Ram Janmabhoomi'],
    district: 'Ayodhya',
    category: 'spiritual',
    description: 'Official prasad box from the Ram Janmabhoomi Trust containing laddoo prasad, sacred kumkum, akshata (rice), and a small Ram Mandir photo. Packaged in a decorative saffron box with Ram Mandir artwork. A sacred souvenir from the newly inaugurated Ram Mandir.',
    shortDescription: 'Official Ram Mandir prasad box — laddoo, kumkum and sacred items.',
    price: 251,
    originalPrice: 251,
    coverImage: 'https://images.unsplash.com/photo-1609893498571-7a45f71e5fe0?w=500',
    seller: { name: 'Ram Janmabhoomi Trust', contact: '+91-9876543220', address: 'Ram Mandir, Ayodhya' },
    stock: 200,
    rating: 4.9,
    reviewCount: 450,
    tags: ['ram mandir', 'prasad', 'ayodhya', 'spiritual', 'sacred'],
    isFeatured: true,
    isActive: true,
  },

  // ── Dudhwa — Nature ───────────────────────────────────
  {
    name: 'Dudhwa Organic Forest Honey',
    slug: 'dudhwa-organic-honey-' + Date.now() + 11,
    destination: destMap['Dudhwa National Park'],
    district: 'Lakhimpur Kheri',
    category: 'food',
    description: 'Wild-harvested organic honey from the forests of Dudhwa National Park. Collected by tribal honey-hunters using traditional sustainable methods. Rich, dark and full of the biodiversity of the terai forest. Each jar supports local tribal communities living around the park.',
    shortDescription: 'Wild organic honey from Dudhwa\'s terai forests — supports tribal communities.',
    price: 380,
    originalPrice: 450,
    coverImage: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500',
    seller: { name: 'Dudhwa Tribal Collective', contact: '+91-9876543221', address: 'Dudhwa Buffer Zone' },
    stock: 55,
    rating: 4.6,
    reviewCount: 72,
    tags: ['honey', 'organic', 'forest', 'tribal', 'natural'],
    isFeatured: false,
    isActive: true,
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB connected for seeding...');

    await Destination.deleteMany();
    await Hotel.deleteMany();
    await User.deleteMany();
    console.log('Cleared existing data');

    await User.create({
      name: 'Admin',
      email: 'admin@upyatra.com',
      password: 'admin123',
      role: 'admin',
    });
    await User.create({
      name: 'Test User',
      email: 'user@upyatra.com',
      password: 'user123',
      role: 'user',
    });
    console.log('Users created');

    const createdDestinations = await Destination.insertMany(destinations);
    console.log(`Seeded ${createdDestinations.length} destinations`);

    const destMap = {};
    createdDestinations.forEach((dest) => {
      destMap[dest.name] = dest._id;
    });

    const hotelData = getHotels(destMap);
    const createdHotels = await Hotel.insertMany(hotelData);
    console.log(`Seeded ${createdHotels.length} hotels`);

    // Clear products and orders too
    await User.deleteMany({ role: 'admin' });

    // Seed products
    const productData = getProducts(destMap);
    const createdProducts = await Product.insertMany(productData);
    console.log(`Seeded ${createdProducts.length} products`);

    console.log('\n✅ Seed complete!');
    console.log(`  ${createdDestinations.length} destinations across all categories`);
    console.log(`  ${createdHotels.length} hotels`);
    console.log('  Admin: admin@upyatra.com / admin123');
    console.log('  User:  user@upyatra.com / user123');
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err.message);
    process.exit(1);
  }
};

seedDB();